source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/TaranWu/Go23WalletSpec.git'


platform :ios, '13.0'
inhibit_all_warnings!

target 'Go23WalletSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'IQKeyboardManager'
  pod 'Alamofire','4.9.1'
  pod 'SDWebImage'
  pod 'SDWebImageWebPCoder'
  pod 'MJRefresh', '3.7.2'
  pod 'FDFullscreenPopGesture'

  pod 'BigInt'
  pod 'MBProgressHUD'
  pod 'SnapKit'
  pod 'KeepLayout', :git => 'https://github.com/iMartinKiss/KeepLayout.git'
  pod 'SwiftyJSON'
  

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['LD_NO_PIE'] = 'NO'
          config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
          config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
          config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      end
  end
end
